## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [6]:
import os
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 設定 data_path
dir_data = 'D:/Rebecca/2nd-ML100Days/GitHub/2nd-ML100Days/data/Part01'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: D:/Rebecca/2nd-ML100Days/GitHub/2nd-ML100Days/data/Part01\application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [28]:
(app_train_row, app_train_column) = app_train.shape
print('資料的row數: %d' % app_train_row)
print('資料的column數: %d' % app_train_column)

資料的row數: 307511
資料的column數: 122

#### 列出所有欄位

In [30]:
print(app_train.columns)

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [40]:
output = app_train[app_train.loc[:,"NAME_CONTRACT_TYPE"] == 'Revolving loans']
print(output)

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
2           100004       0    Revolving loans           M            Y
9           100012       0    Revolving loans           M            N
17          100021       0    Revolving loans           F            N
18          100022       0    Revolving loans           F            N
20          100024       0    Revolving loans           M            Y
29          100034       0    Revolving loans           M            N
39          100046       0    Revolving loans           M            Y
45          100052       0    Revolving loans           F            N
50          100058       0    Revolving loans           F            N
57          100068       0    Revolving loans           M            N
67          100079       0    Revolving loans           M            N
68          100080       0    Revolving loans           F            N
76          100088       0    Revolving loans           F            N
80          100095       0    Revolving loans           F            N
83          100098       0    Revolving loans           M            Y
100         100119       0    Revolving loans           F            N
107         100126       0    Revolving loans           M            N
109         100129       0    Revolving loans           F            Y
114         100134       0    Revolving loans           F            N
120         100140       0    Revolving loans           F            N
122         100143       0    Revolving loans           M            N
132         100154       0    Revolving loans           M            N
147         100174       0    Revolving loans           F            N
155         100182       0    Revolving loans           F            N
165         100194       0    Revolving loans           F            N
180         100209       1    Revolving loans           M            N
194         100226       0    Revolving loans           F            N
198         100230       0    Revolving loans           F            N
201         100234       0    Revolving loans           F            N
233         100270       0    Revolving loans           F            N
...            ...     ...                ...         ...          ...
307129      455825       0    Revolving loans           F            N
307133      455830       1    Revolving loans           F            N
307137      455834       0    Revolving loans           F            N
307184      455887       0    Revolving loans           M            N
307188      455891       0    Revolving loans           F            N
307199      455904       0    Revolving loans           M            Y
307209      455917       0    Revolving loans           F            N
307210      455918       0    Revolving loans           F            N
307220      455928       0    Revolving loans           M            Y
307226      455934       0    Revolving loans           F            Y
307234      455943       0    Revolving loans           F            Y
307235      455944       0    Revolving loans           F            N
307286      456003       0    Revolving loans           F            Y
307287      456004       0    Revolving loans           F            Y
307298      456021       0    Revolving loans           F            N
307302      456025       0    Revolving loans           F            N
307314      456038       0    Revolving loans           F            N
307332      456056       0    Revolving loans           M            N
307372      456097       0    Revolving loans           M            N
307375      456100       0    Revolving loans           F            N
307384      456109       0    Revolving loans           M            N
307385      456110       0    Revolving loans           M            Y
307402      456135       0    Revolving loans           F            N
307419      456152       0    Revolving loans           F            N
307425      456158       0    Revolving loans           M            Y
307444      456182       0    Revolving loans           F            N
307457      456196       0    Revolving loans           F            N
307467      456207       0    Revolving loans           F            N
307485      456229       0    Revolving loans           F            N
307496      456240       0    Revolving loans           F            N

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
2                    Y             0           67500.0    135000.0
9                    Y             0          135000.0    405000.0
17                   Y             1           81000.0    270000.0
18                   Y             0          112500.0    157500.0
20                   Y             0          135000.0    427500.0
29                   Y             0           90000.0    180000.0
39                   Y             0          180000.0    540000.0
45                   Y             1           90000.0    180000.0
50                   Y             0           54000.0    135000.0
57                   Y             0           81000.0    247500.0
67                   Y             0          225000.0    270000.0
68                   N             1          157500.0    450000.0
76                   N             0          112500.0    135000.0
80                   Y             2           67500.0    135000.0
83                   N             0          225000.0    270000.0
100                  Y             0           54000.0    180000.0
107                  Y             2          135000.0    180000.0
109                  Y             1           85500.0    135000.0
114                  N             0          202500.0    180000.0
120                  N             0          157500.0    675000.0
122                  Y             0          162000.0    270000.0
132                  N             0          144000.0    180000.0
147                  Y             2          180000.0    225000.0
155                  Y             1          112500.0    135000.0
165                  Y             2          157500.0    315000.0
180                  Y             3          180000.0    540000.0
194                  N             2          112500.0    270000.0
198                  N             0          135000.0    405000.0
201                  N             0           67500.0    180000.0
233                  Y             0           90000.0    337500.0
...                ...           ...               ...         ...
307129               Y             0          360000.0    765000.0
307133               Y             0           90000.0    135000.0
307137               Y             0          139500.0    180000.0
307184               Y             0          157500.0    202500.0
307188               Y             0          180000.0    382500.0
307199               Y             2          202500.0    270000.0
307209               Y             0          180000.0    270000.0
307210               Y             0           72000.0    157500.0
307220               Y             0          135000.0    270000.0
307226               Y             0          166500.0    225000.0
307234               N             0           72000.0    180000.0
307235               Y             0           63000.0    180000.0
307286               Y             2           90000.0    180000.0
307287               Y             0          135000.0    405000.0
307298               Y             0          180000.0    405000.0
307302               Y             0          144000.0    180000.0
307314               N             1          121500.0    382500.0
307332               Y             1          193500.0    180000.0
307372               Y             0          112500.0    180000.0
307375               Y             0           63000.0    135000.0
307384               N             0          180000.0    270000.0
307385               Y             2          180000.0    180000.0
307402               Y             0          157500.0    382500.0
307419               N             1          112500.0    450000.0
307425               Y             2          234000.0    450000.0
307444               Y             2           90000.0    270000.0
307457               Y             2          202500.0    360000.0
307467               Y             0          247500.0    675000.0
307485               Y             1          270000.0    180000.0
307496               N             0          360000.0    337500.0

        AMT_ANNUITY             ...              FLAG_DOCUMENT_18  \
2            6750.0             ...                             0
9           20250.0             ...                             0
17          13500.0             ...                             0
18           7875.0             ...                             0
20          21375.0             ...                             0
29           9000.0             ...                             0
39          27000.0             ...                             0
45           9000.0             ...                             0
50           6750.0             ...                             1
57          12375.0             ...                             0
67          13500.0             ...                             0
68          22500.0             ...                             0
76           6750.0             ...                             0
80           6750.0             ...                             0
83          13500.0             ...                             0
100          9000.0             ...                             0
107          9000.0             ...                             0
109          6750.0             ...                             0
114          9000.0             ...                             0
120         33750.0             ...                             0
122         13500.0             ...                             0
132          9000.0             ...                             0
147         11250.0             ...                             0
155          6750.0             ...                             0
165         15750.0             ...                             0
180         27000.0             ...                             0
194         13500.0             ...                             0
198         20250.0             ...                             0
201          9000.0             ...                             0
233         16875.0             ...                             0
...             ...             ...                           ...
307129      38250.0             ...                             0
307133       6750.0             ...                             0
307137       9000.0             ...                             0
307184      10125.0             ...                             0
307188      19125.0             ...                             0
307199      13500.0             ...                             0
307209      13500.0             ...                             0
307210       7875.0             ...                             0
307220      13500.0             ...                             0
307226      11250.0             ...                             0
307234       9000.0             ...                             0
307235       9000.0             ...                             0
307286       9000.0             ...                             0
307287      20250.0             ...                             0
307298      20250.0             ...                             0
307302       9000.0             ...                             0
307314      19125.0             ...                             0
307332       9000.0             ...                             0
307372       9000.0             ...                             0
307375       6750.0             ...                             0
307384      13500.0             ...                             0
307385       9000.0             ...                             0
307402      19125.0             ...                             0
307419      22500.0             ...                             0
307425      22500.0             ...                             0
307444      13500.0             ...                             0
307457      18000.0             ...                             0
307467      33750.0             ...                             0
307485       9000.0             ...                             0
307496      16875.0             ...                             0

       FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
2                     0                0                0
9                     0                0                0
17                    0                0                0
18                    0                0                0
20                    0                0                0
29                    0                0                0
39                    0                0                0
45                    0                0                0
50                    0                0                0
57                    0                0                0
67                    0                0                0
68                    0                0                0
76                    0                0                0
80                    0                0                0
83                    0                0                0
100                   0                0                0
107                   0                0                0
109                   0                0                0
114                   0                0                0
120                   0                0                0
122                   0                0                0
132                   0                0                0
147                   0                0                0
155                   0                0                0
165                   0                0                0
180                   0                0                0
194                   0                0                0
198                   0                0                0
201                   0                0                0
233                   0                0                0
...                 ...              ...              ...
307129                0                0                0
307133                0                0                0
307137                0                0                0
307184                0                0                0
307188                0                0                0
307199                0                0                0
307209                0                0                0
307210                0                0                0
307220                0                0                0
307226                0                0                0
307234                0                0                0
307235                0                0                0
307286                0                0                0
307287                0                0                0
307298                0                0                0
307302                0                0                0
307314                0                0                0
307332                0                0                0
307372                0                0                0
307375                0                0                0
307384                0                0                0
307385                0                0                0
307402                0                0                0
307419                0                0                0
307425                0                0                0
307444                0                0                0
307457                0                0                0
307467                0                0                0
307485                0                0                0
307496                0                0                0

       AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
2                             0.0                       0.0
9                             NaN                       NaN
17                            NaN                       NaN
18                            0.0                       0.0
20                            NaN                       NaN
29                            NaN                       NaN
39                            0.0                       0.0
45                            NaN                       NaN
50                            0.0                       0.0
57                            0.0                       0.0
67                            0.0                       0.0
68                            0.0                       0.0
76                            0.0                       0.0
80                            NaN                       NaN
83                            NaN                       NaN
100                           0.0                       0.0
107                           0.0                       0.0
109                           1.0                       0.0
114                           0.0                       0.0
120                           NaN                       NaN
122                           0.0                       0.0
132                           0.0                       0.0
147                           0.0                       0.0
155                           0.0                       0.0
165                           0.0                       0.0
180                           0.0                       0.0
194                           NaN                       NaN
198                           0.0                       0.0
201                           0.0                       0.0
233                           0.0                       0.0
...                           ...                       ...
307129                        NaN                       NaN
307133                        0.0                       0.0
307137                        0.0                       0.0
307184                        0.0                       0.0
307188                        0.0                       0.0
307199                        0.0                       0.0
307209                        0.0                       0.0
307210                        0.0                       0.0
307220                        0.0                       0.0
307226                        0.0                       0.0
307234                        0.0                       0.0
307235                        0.0                       0.0
307286                        0.0                       0.0
307287                        0.0                       0.0
307298                        0.0                       0.0
307302                        0.0                       1.0
307314                        0.0                       0.0
307332                        0.0                       0.0
307372                        NaN                       NaN
307375                        0.0                       0.0
307384                        0.0                       0.0
307385                        0.0                       0.0
307402                        0.0                       0.0
307419                        0.0                       0.0
307425                        0.0                       0.0
307444                        0.0                       0.0
307457                        0.0                       0.0
307467                        0.0                       0.0
307485                        0.0                       0.0
307496                        0.0                       0.0


#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子